docker_java_17: &docker_java_17
  docker:
    - image: cimg/openjdk:17.0.2-node
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
jobs:
  build:
    <<: *docker_java_17
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "5f:9d:14:91:16:7c:39:92:67:55:6d:78:65:7e:f4:64"
      - checkout
      - run:
          name: Deploy artifacts to nexus
          command: |
            cd contracts
            mvn deploy -s ~/repo/.circleci/settings.xml -DskipTests=true
